### ISSUE TITLE
Possible stack attack

### ISSUE THREAD

**Issue by davedoesdev** [apowers313/fido2-lib#11]
This line:

https://github.com/apowers313/fido2-lib/blob/master/lib/parser.js#L102

```javascript
var clientDataJson = String.fromCharCode.apply(null, new Uint8Array(clientDataJSON));
```

Won't this bust the stack if `clientDataJSON` is long? Since this is client-supplied data, perhaps its length should be sanity checked?

**Comment by apowers313** [comment]
Good question, I’ll take a look at rewriting it. And thanks for the review.

**Comment by apowers313** [comment]
Quick demo code to prove that this is actually problem:

``` js
"use strict";

var clientDataJSON = new ArrayBuffer(1024000);
var converted = String.fromCharCode.apply(null, new Uint8Array(clientDataJSON));
console.log("converted", converted);
```

Results in:

> RangeError: Maximum call stack size exceeded
    at Object.<anonymous> (/Users/apowers/Projects/proto/stack-attack/test.js:4:37)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
